# -*- coding: utf-8 -*-
"""MemAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EO8wcF5L97-9oknJk72Q703tL0MLXFY9

### Try on SQL Lite
"""

!pip install -q memori openai

from google.colab import userdata
api_key = userdata.get('openai_api_key')

from openai import OpenAI, AsyncOpenAI
client = AsyncOpenAI(api_key=api_key)

from memori import Memori
import sqlite3

def get_sqlite_connection():
    return sqlite3.connect("memori.db")


memori = Memori(conn=get_sqlite_connection).llm.register(client)
memori.attribution(entity_id="123456", process_id="test-ai-agent")
memori.config.storage.build()

# Define the coroutine for making API calls to GPT
async def make_api_call_to_gpt(prompt, model="gpt-4o-mini"):
    messages = [{"role": "user", "content": prompt}]
    response =  await client.chat.completions.create(
        model=model,
        messages=messages,
        temperature=0,
    )

    return response.choices[0].message.content

import asyncio
task = make_api_call_to_gpt("Blue is my favorite color")
result = await asyncio.gather(task)
print(result)

import asyncio
task = make_api_call_to_gpt("What is my favorite color?")
result = await asyncio.gather(task)
print(result)

"""### Install PostgresDB"""

!sudo apt-get -y -qq update
!sudo apt-get -y -qq install postgresql

!sudo service postgresql start

!sudo -u postgres psql -U postgres -c "ALTER USER postgres PASSWORD 'postgres';"

!sudo -u postgres psql -U postgres -c "CREATE DATABASE memoridb OWNER postgres;"

!pip install -q psycopg2-binary

from memori import Memori
import psycopg2

def get_postgres_connection():
    return psycopg2.connect(database="memoridb", user="postgres", password="postgres", host="localhost", port=5432)



memori = Memori(conn=get_postgres_connection).llm.register(client)
memori.attribution(entity_id="123456", process_id="test-ai-agent")
memori.config.storage.build()

import asyncio
task = make_api_call_to_gpt("Blue is my favorite color")
result = await asyncio.gather(task)
print(result)

import asyncio
task = make_api_call_to_gpt("What is my favorite color?")
result = await asyncio.gather(task)
print(result)